
package client.core.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "IllegalParameterException", targetNamespace = "http://webservice.core/")
public class IllegalParameterException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MovieServiceFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public IllegalParameterException(String message, MovieServiceFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public IllegalParameterException(String message, MovieServiceFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: client.core.webservice.MovieServiceFault
     */
    public MovieServiceFault getFaultInfo() {
        return faultInfo;
    }

}
