
package com.wishmaster.ifmo.ws.jaxws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MovieWebService", targetNamespace = "http://webservice.core/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MovieWebService {


    /**
     * 
     * @param rating
     * @return
     *     returns java.util.List<com.wishmaster.ifmo.ws.jaxws.client.Movie>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectByRating", targetNamespace = "http://webservice.core/", className = "com.wishmaster.ifmo.ws.jaxws.client.SelectByRating")
    @ResponseWrapper(localName = "selectByRatingResponse", targetNamespace = "http://webservice.core/", className = "com.wishmaster.ifmo.ws.jaxws.client.SelectByRatingResponse")
    public List<Movie> selectByRating(
        @WebParam(name = "rating", targetNamespace = "")
        int rating);

    /**
     * 
     * @param name
     * @return
     *     returns java.util.List<com.wishmaster.ifmo.ws.jaxws.client.Movie>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectByName", targetNamespace = "http://webservice.core/", className = "com.wishmaster.ifmo.ws.jaxws.client.SelectByName")
    @ResponseWrapper(localName = "selectByNameResponse", targetNamespace = "http://webservice.core/", className = "com.wishmaster.ifmo.ws.jaxws.client.SelectByNameResponse")
    public List<Movie> selectByName(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param year
     * @return
     *     returns java.util.List<com.wishmaster.ifmo.ws.jaxws.client.Movie>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectByYear", targetNamespace = "http://webservice.core/", className = "com.wishmaster.ifmo.ws.jaxws.client.SelectByYear")
    @ResponseWrapper(localName = "selectByYearResponse", targetNamespace = "http://webservice.core/", className = "com.wishmaster.ifmo.ws.jaxws.client.SelectByYearResponse")
    public List<Movie> selectByYear(
        @WebParam(name = "year", targetNamespace = "")
        int year);

    /**
     * 
     * @return
     *     returns java.util.List<com.wishmaster.ifmo.ws.jaxws.client.Movie>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectAll", targetNamespace = "http://webservice.core/", className = "com.wishmaster.ifmo.ws.jaxws.client.SelectAll")
    @ResponseWrapper(localName = "selectAllResponse", targetNamespace = "http://webservice.core/", className = "com.wishmaster.ifmo.ws.jaxws.client.SelectAllResponse")
    public List<Movie> selectAll();

    /**
     * 
     * @param director
     * @return
     *     returns java.util.List<com.wishmaster.ifmo.ws.jaxws.client.Movie>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectByDirector", targetNamespace = "http://webservice.core/", className = "com.wishmaster.ifmo.ws.jaxws.client.SelectByDirector")
    @ResponseWrapper(localName = "selectByDirectorResponse", targetNamespace = "http://webservice.core/", className = "com.wishmaster.ifmo.ws.jaxws.client.SelectByDirectorResponse")
    public List<Movie> selectByDirector(
        @WebParam(name = "director", targetNamespace = "")
        String director);

    /**
     * 
     * @param genre
     * @return
     *     returns java.util.List<com.wishmaster.ifmo.ws.jaxws.client.Movie>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectByGenre", targetNamespace = "http://webservice.core/", className = "com.wishmaster.ifmo.ws.jaxws.client.SelectByGenre")
    @ResponseWrapper(localName = "selectByGenreResponse", targetNamespace = "http://webservice.core/", className = "com.wishmaster.ifmo.ws.jaxws.client.SelectByGenreResponse")
    public List<Movie> selectByGenre(
        @WebParam(name = "genre", targetNamespace = "")
        String genre);

    /**
     * 
     * @param id
     * @return
     *     returns com.wishmaster.ifmo.ws.jaxws.client.Movie
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectById", targetNamespace = "http://webservice.core/", className = "com.wishmaster.ifmo.ws.jaxws.client.SelectById")
    @ResponseWrapper(localName = "selectByIdResponse", targetNamespace = "http://webservice.core/", className = "com.wishmaster.ifmo.ws.jaxws.client.SelectByIdResponse")
    public Movie selectById(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param rating
     * @param genre
     * @return
     *     returns java.util.List<com.wishmaster.ifmo.ws.jaxws.client.Movie>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectByRatingAndGenre", targetNamespace = "http://webservice.core/", className = "com.wishmaster.ifmo.ws.jaxws.client.SelectByRatingAndGenre")
    @ResponseWrapper(localName = "selectByRatingAndGenreResponse", targetNamespace = "http://webservice.core/", className = "com.wishmaster.ifmo.ws.jaxws.client.SelectByRatingAndGenreResponse")
    public List<Movie> selectByRatingAndGenre(
        @WebParam(name = "rating", targetNamespace = "")
        String rating,
        @WebParam(name = "genre", targetNamespace = "")
        String genre);

    /**
     * 
     * @param year
     * @param rating
     * @return
     *     returns java.util.List<com.wishmaster.ifmo.ws.jaxws.client.Movie>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectByYearAndRating", targetNamespace = "http://webservice.core/", className = "com.wishmaster.ifmo.ws.jaxws.client.SelectByYearAndRating")
    @ResponseWrapper(localName = "selectByYearAndRatingResponse", targetNamespace = "http://webservice.core/", className = "com.wishmaster.ifmo.ws.jaxws.client.SelectByYearAndRatingResponse")
    public List<Movie> selectByYearAndRating(
        @WebParam(name = "year", targetNamespace = "")
        String year,
        @WebParam(name = "rating", targetNamespace = "")
        String rating);

    /**
     * 
     * @param year
     * @param genre
     * @return
     *     returns java.util.List<com.wishmaster.ifmo.ws.jaxws.client.Movie>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectByYearAndGenre", targetNamespace = "http://webservice.core/", className = "com.wishmaster.ifmo.ws.jaxws.client.SelectByYearAndGenre")
    @ResponseWrapper(localName = "selectByYearAndGenreResponse", targetNamespace = "http://webservice.core/", className = "com.wishmaster.ifmo.ws.jaxws.client.SelectByYearAndGenreResponse")
    public List<Movie> selectByYearAndGenre(
        @WebParam(name = "year", targetNamespace = "")
        String year,
        @WebParam(name = "genre", targetNamespace = "")
        String genre);

}
