
package com.wishmaster.ifmo.ws.jaxws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MovieService", targetNamespace = "http://webservice.core/", wsdlLocation = "http://localhost:8080/MovieService?wsdl")
public class MovieService
    extends Service
{

    private final static URL MOVIESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.wishmaster.ifmo.ws.jaxws.client.MovieService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.wishmaster.ifmo.ws.jaxws.client.MovieService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/MovieService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/MovieService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MOVIESERVICE_WSDL_LOCATION = url;
    }

    public MovieService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MovieService() {
        super(MOVIESERVICE_WSDL_LOCATION, new QName("http://webservice.core/", "MovieService"));
    }

    /**
     * 
     * @return
     *     returns MovieWebService
     */
    @WebEndpoint(name = "MovieWebServicePort")
    public MovieWebService getMovieWebServicePort() {
        return super.getPort(new QName("http://webservice.core/", "MovieWebServicePort"), MovieWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MovieWebService
     */
    @WebEndpoint(name = "MovieWebServicePort")
    public MovieWebService getMovieWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.core/", "MovieWebServicePort"), MovieWebService.class, features);
    }

}
